name: RunLinter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run lint
